config/routes.rb
Games::Application.routes.draw do

  devise_for :users

  root 'home#index'

  resources :my_games, only: [:index, :create, :destroy], path: :games

end

app/models/game.rb
class Game < ActiveRecord::Base

	has_many :user_games, dependent: :destroy
	has_many :users, through: :user_games
  validates :title, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  has_many :user_games, dependent: :destroy
  has_many :games, -> { order 'title' }, through: :user_games

	def add_game(game)
		games << game unless games.include?(game)
	end

	def add_game_by_title(title)
		existing_game = Game.where('title ilike ?', title).limit(1).try(:first)
		game = existing_game || Game.create(title: format_title(title))
		add_game(game)
	end

	def remove_game(game)
		if games.include?(game)
			games.destroy(game)
			game.destroy if game.users.empty?
		end
	end

	private

	def format_title(title)
		title.downcase.titleize
	end

end

app/models/user_game.rb
class UserGame < ActiveRecord::Base

  belongs_to :user
  belongs_to :game

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(user)
    my_games_path
  end

  def after_sign_out_path_for(user)
    root_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
		redirect_to my_games_path if current_user
  end

end

app/controllers/my_games_controller.rb
class MyGamesController < ApplicationController

  before_action :authenticate_user!

  def index
    @games = current_user.games
  end

	def create
		user = current_user
		user.add_game_by_title(params[:game][:title]) if params[:game][:title].present?
		@games = user.games
		respond_to do |format|
			format.js { render partial: 'games' }
		end
	end

	def destroy
		user = current_user
		game = Game.find(params[:id])
		user.remove_game(game)
		@games = user.games
		respond_to do |format|
			format.js { render partial: 'games' }
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
= content_for(:title) { 'Games List' }

.row
  .large-12.columns.text-center
    %header.main-title
      %h1 Welcome to Games List
      %p Track the board games you and your friends own
.row
  .large-12.columns.text-center.home-buttons
    = link_to 'Login', new_user_session_path, class: 'button'
    = link_to 'Signup', new_user_registration_path, class: 'button'

app/views/layouts/application.html.haml
!!! 5
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class="ie6" lang="en">
/[if IE 7 ]    <html class="ie7" lang="en">
/[if IE 8 ]    <html class="ie8" lang="en">
/[if (gte IE 9)|!(IE)]><! --> <html lang="en"> <!--

%head

  %meta(charset="utf-8")
  %meta(name="viewport" content="width=device-width, initial-scale=1.0")
  %title= content_for?(:title) ? yield(:title) : "Untitled"
  = stylesheet_link_tag "application"
  = javascript_include_tag "vendor/custom.modernizr"
  = csrf_meta_tags

%body

  = render partial: 'shared/top_bar'
  = render partial: 'shared/alerts'

  %section.main.row
    .large-12.columns
      = yield

  = javascript_include_tag "application"

:plain
  </html>

app/views/my_games/_games.html.haml
%ul.unstyled.games
  - @games.each do |game|
    %li.row
      .large-12.columns
        %span.title= game.title
        = link_to my_game_path(game), method: :delete, remote: true, class: 'remove-game-link' do
          %i.icon-remove-circle

app/views/my_games/_games.js.erb
$("input[name='game[title]']").val('');
$("#games").html("<%= escape_javascript(render partial: 'games', formats: [:html], locals: { flash: flash } ) %>");
if($('#toggle-edit-mode').hasClass('edit-mode')) {
	$('.remove-game-link').show();
}

app/views/my_games/index.html.haml
%h1 My Games

%section.add-game-form-section
  = form_tag my_games_path, remote: true do
    .row
      .large-12.columns
        %input.game-title-input.large-6.small-8.columns(type="text" name="game[title]" placeholder="Game Title")
        %button.add-game-button(type="submit")
          %i.icon-plus-sign-alt
        %a#toggle-edit-mode.remove-games-button(href='#')
          %i.icon-minus-sign-alt

%section#games
  = render 'games'

app/views/shared/_alerts.html.haml
%section.alerts.row
  .large-12.columns
    - flash.each do |type, msg|
      - next if msg.blank?
      .alert-box(data-alert)
        = msg
        %a.close(href="#") &times;

app/views/shared/_alerts.js.erb
$(".alerts").html("<%=
  escape_javascript(render partial: 'shared/alerts', formats: [:html], locals: { flash: flash } )
%>");

app/views/shared/_top_bar.html.haml
%nav.top-bar

  %ul.title-area
    %li.name
      %h1= link_to 'Games List', user_signed_in? ? my_games_path : root_path
    %li.toggle-topbar.menu-icon
      %a(href="#")
        %span Menu

  %section.top-bar-section
    %ul.right
      - if user_signed_in?
        %li= link_to 'Logout', destroy_user_session_path, method: :delete
        %li= link_to 'Edit Profile', edit_user_registration_path
      - else
        %li= link_to 'Login', new_user_session_path
        %li= link_to 'Sign Up', new_user_registration_path